version: '0.1'

services:
  chat-app:
    image: chat-app
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
      environment:
        NODE_ENV: development
#    volumes:
#      - ../server/:/usr/src/app/server
#      - /usr/src/app/server/node_modules